@startuml
left header
	<font color=000 size=18><b>Package:</b> AD_1.1
	<font color=000 size=16><b>ID:</b> UC_1
	<font color=000 size=16><b>Назва:</b> Реєстрація
	<font color=000 size=16><b>Учасники:</b> Користувач, Web-система
	<font color=000 size=16><b>Передумови:</b> Користувач знаходиться на Web-сторінці
	<font color=000 size=16><b>Результат:</b> Користувач зареєстрований, дані занесені до бази
	<font color=000 size=16><b>Виключні ситуації:</b>
	<font color=000 size=16> EX_1.1 Користувач заповнює форму реєстрації некоректними даними;
	<font color=000 size=16> EX_1.2 Користувач з таким e-mail уже зареєстрований;
	<font color=000 size=16> EX_1.3 Введені паролі не співпадають;
	<font color=000 size=16> EX_1.4 Необхідні поля не помічені галочками;
	<font color=000 size=16><b>Основний сценарій:</b>
end header

|Користувач|
	start
	: Натискає кнопку реєстрації;
|Web-система|
	: Відображає форму реєстрації;
|Користувач|
	:заповнює форму реєстрації коректними даними 
	(ім’я, e-mail, пароль, підтвердження пароля)
	та помічає необхідні поля галочками;
	: Натискає кнопку підтвердження;
|Web-система|
	:Підтверджує правильність заповненої форми;
	
	note right #ffaaaa
		<b> Можливо
		<b> EX_1.1
		<b> EX_1.2
		<b> EX_1.3
		<b> EX_1.4
	end note

	: Реєструє користувача;
	
	note right 
		Відповідні дані
		користувача заносяться 
		до бази даних
	end note

	: Надсилає на e-mail лист із підтвердженням;
|Користувач|
    : Отримує доступ до облікового запису;
	stop;
@enduml